blog_app/urls.py
from django.conf.urls import url,include
from blog_app import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'blog_app'

urlpatterns = [
            url(r'^$',views.PostList.as_view(),name='post_list'),
            url(r'^post/(?P<pk>\d+)/add/$',views.add_friend,name='add_frnd'),
            url(r'^user/(?P<pk>\d+)/profile/$',views.user_profile,name='user_prof'),
            url(r'^listuser/$',views.ListUser.as_view(),name='list_user'),
            url(r'^post/(?P<pk>\d+)/friendlist/$',views.friend_list,name='frnd_list'),
            url(r'^about/$',views.AboutView.as_view(),name='about'),
            url(r'^post/(?P<pk>\d+)/$',views.BlogPost.as_view(),name='blog_post'),
            url(r'^post/login/$',views.CreatePost.as_view(),name='post_login'),
            url(r'^post/(?P<pk>\d+)/edit/$',views.BlogUpdate.as_view(),name='post_edit'),
            url(r'^post/(?P<pk>\d+)/delete$',views.PostDelete.as_view(),name='post_delete'),
            url(r'^drafts/$',views.DraftList.as_view(),name='drafts_list'),
            url(r'^post/(?P<pk>\d+)/comment/$',views.add_comment_to_post,name='post_comment'),
            url(r'^post/(?P<pk>\d+)/approve/$',views.comment_approval,name='comment_approval'),
            url(r'^post/(?P<pk>\d+)/delete/$',views.comment_delete,name='comment_delete'),
            url(r'^post/(?P<pk>\d+)/publish/$',views.publish_post,name='publish_post'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog_project/urls.py
from django.contrib import admin
from django.contrib.auth.views import login,logout
from django.conf.urls import url,include
from blog_app import views,urls

urlpatterns = [
    url('admin/', admin.site.urls),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'',include('blog_app.urls')),
    url(r'accounts/login/$',login,name='login'),
    url(r'accounts/logout/$',logout,name='logout',kwargs={'next_page':'login'})
]

blog_app/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
    user_p = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pic/',blank=True,null=True)

class Post(models.Model):
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now())
    published_date = models.DateTimeField(blank=True,null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('blog_app.Post',on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now())
    approved_comment = models.BooleanField(default=False)


    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):  # after approving the comment,it will display list of posts
        return reverse('post_list')

    def __str__(self):
        return self.text

class Friend(models.Model):
    users = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, related_name='owner',null=True,on_delete=models.CASCADE)

blog_app/forms.py
from django import forms
from blog_app.models import Post,Comment,UserProfileInfo

class PostForm(forms.ModelForm):

    class Meta():
        model = Post
        fields = ('title','text')

        widgets = {
        'title' : forms.TextInput(attrs = {'class':'textinputclass'}),
        'text' : forms.Textarea(attrs = {'class':'editable medium-editor-textarea postcontent'})
        }

class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ('author','text')

        widgets = {
        'author': forms.TextInput(attrs = {'class':'textinputclass'}),
        'text' : forms.Textarea(attrs = {'class':'editable medium-editor-textarea'})
        }


class ProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('profile_pic',)

blog_app/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import (TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from blog_app.forms import PostForm,CommentForm,ProfileForm
from blog_app.models import Post,Comment,Friend,UserProfileInfo
from django.contrib.auth.models import User

# Create your views here.


class AboutView(TemplateView):
    template_name = "about.html"

class ListUser(ListView):
    model = User
    template_name = 'list_user.html'

class PostList(ListView):
    model = Post
    template_name = "post_list.html"
    def get_context_data(self, *args, **kwargs):
        context = super(PostList, self).get_context_data(*args, **kwargs)
        usr = User.objects.get(username=self.request.user.username)
        friendss = Friend.objects.get(current_user=usr)
        context['friends'] = friendss.users.all()
        return context


class BlogPost(DetailView):
    model = Post
    template_name = "post_detail.html"
    def get_context_data(self, *args, **kwargs):
        context = super(BlogPost, self).get_context_data(*args, **kwargs)
        usr = get_object_or_404(Post,pk=self.kwargs["pk"])
        comment = Comment.objects.filter(post=usr)
        context['comment'] = comment.all()
        return context

class CreatePost(CreateView):
    template_name = "post_form.html"
    form_class = PostForm
    model=Post
    def form_valid(self, form):
        self.object=form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return redirect("blog_app:post_list")



class BlogUpdate(LoginRequiredMixin,UpdateView):
        login_url = '/login/'
        redirect_field_name = 'blog_app/post_detail.html'
        form_class = PostForm
        template_name = "post_form.html"
        model=Post
        def form_valid(self, form):
            self.object=form.save(commit=False)
            self.object.author = self.request.user
            self.object.save()
            return redirect("blog_app:post_list")


class PostDelete(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('post_list')


class DraftList(LoginRequiredMixin,ListView):
    login_url = '/login/'
    redirect_field_name = 'blog_app/post_list.html'
    model = Post

    def get_queryset(self):
        return Post.object.filter(published_date__isnull=True.order_by('created_date'))



@login_required
def add_comment_to_post(request,pk):
    post_com = get_object_or_404(Post,pk=pk)
    if request.method == 'POST':
        form_c = CommentForm(request.POST)
        if form_c.is_valid():
            form_comments = form_c.save(commit=False)
            form_comments.post = post_com
            form_comments.save()
            return redirect ('blog_app:blog_post',post_com.pk)
    else:
        form_c = CommentForm()
    return render(request,'blog_app/comments_form.html',{'form':form_c})


@login_required
def comment_approval(request,pk):
    comments = get_object_or_404(Comment,pk=pk)
    comment.approve()
    return redirect ('blog_post',comments.post.pk)

@login_required
def comment_delete(request,pk):
    comments = get_object_or_404(Comment,pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect ('blog_post',pk=post_pk)


@login_required
def publish_post(request,pk):
    post = get_object_or_404(Post,pk=pk)
    post.publish()
    return redirect("blog_app:post_list")


@login_required
def add_friend(request,pk):
    login_user = request.user
    usr = get_object_or_404(User,pk=pk)
    friend = Friend.objects.get_or_create(current_user=login_user)
    friend[0].users.add(usr)
    friend2 = Friend.objects.get_or_create(current_user=usr)
    friend2[0].users.add(login_user)
    return redirect("blog_app:list_user")

def friend_list(request,pk):
    usr = get_object_or_404(User,pk=pk)
    friend = Friend.objects.get(current_user=usr)
    fs = friend.users.all()
    return render(request,'blog_app/friend_list.html',{'frnds':fs})


def user_profile(request,pk):
    usr = User.objects.get(pk=pk)
    try:
        pp = request.user.userprofileinfo
    except UserProfileInfo.DoesNotExist:
        pp = UserProfileInfo(user_p=request.user)

    if request.method == 'POST':
        form_t1 = ProfileForm(request.POST,request.FILES ,instance=pp)
        if form_t1.is_valid():
            temp = form_t1.save(commit=False)
            temp.user_p = usr
            temp.save()
    else:
        form_t1 = ProfileForm(instance=pp)
    return render(request,'blog_app/user_profile.html',{ 'pp' : pp , 'form_1' : form_t1 , 'user' : usr })

blog_app/templates/blog_app/about.html
<!DOCTYPE html>
{% extends "blog_app/base.html" %}
{% block content %}
<h1>Maa Chuda Bhosadike</h1>
{% endblock %}

blog_app/templates/blog_app/base.html
<!DOCTYPE html>
{ load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Bloggers</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="{{ STATIC_DIR }}css/blogapp.css">
    <link href="https://fonts.googleapis.com/css?family=Tajawal" rel="stylesheet">
  </head>
  <body>
  <nav class="navbar navbar-inverse navbar-fixed-top blogfont">
    <div class="container-fluid">
      <div class="navbar-header">
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'blog_app:post_list' %}">Bloggers</a>
        {% else %}
        <a class="navbar-brand" href="{% url 'login' %}">Bloggers</a>
        {% endif %}
      </div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="{% url 'blog_app:about' %}">About</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><a href="{% url 'blog_app:user_prof'  pk=request.user.pk %}">Hi, {{user.username}}</a></li>
        <li><a href="{% url 'blog_app:post_login' %}">New Post</a></li>
        <li><a href="{% url 'blog_app:drafts_list' %}">Drafts</a></li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <div class="content container">
    <div class="row">
      <div class="col-md-8">
        <div class="blog_posts">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </div>
  </body>
</html>

blog_app/templates/blog_app/comments_form.html
<!DOCTYPE html>
{% extends "blog_app/base.html" %}
{% block content %}
<div class='jumbotron'>
  <h3> MC likh abhi</h3>
  {% if form.errors %}
    <p>Galat hai bhai!</p>
  {% endif %}
  <form method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
  <input type='submit' class="btn btn-primary" value="Post">
  <input type='hidden' name="next" value="{{next}}">
  </form>

</div>
{% endblock %}

blog_app/templates/blog_app/friend_list.html
<!DOCTYPE html>
{% extends "blog_app/base.html" %}
{% load staticfiles %}
{% block content %}
<div class="container">
Friend List for {{ request.user.username }}:
{% for fr in frnds %}
<h1> <a href="{% url 'blog_app:user_prof'  pk=fr.pk %}">{{ fr.username }} {{ fr.pk }}</a></h1>
{% endfor %}
</div>
{% endblock %}

blog_app/templates/blog_app/list_user.html
<!DOCTYPE html>
{% extends "blog_app/base.html" %}
{% load staticfiles %}
{% block content %}
<div class="centerstage">
  {% for use in user_list %}
  {% if request.user.username == use.username %}
  <h1>{{ use.username }}</h1>
  {% else %}
  <h1><a href="{% url 'blog_app:add_frnd'  pk=use.pk %}">{{ use.username }}</a></h1>
  {% endif %}
  {% endfor %}
</div>
Friend List for <a href="{% url 'blog_app:frnd_list'  pk=request.user.pk %}">{{ request.user.username }}</a>:
{% endblock %}

blog_app/templates/blog_app/post_confirm_delete.html
<!DOCTYPE html>
{% extends "blog_app/base.html" %}
{% block content %}
{% endblock %}

blog_app/templates/blog_app/post_detail.html
<!DOCTYPE html>
{% extends "blog_app/base.html" %}
{% block content %}
<h1>{{post.title}}</h1>
<p> {{post.text}} </p>
{% if post.published_date %}
{{post.published_date}}
{% else %}
{% if user.is_authenticated %}
<a class='btn btn-primary' href="{% url 'blog_app:publish_post' pk=post.pk %}">Publish</a>
<a class='btn btn-primary' href="{% url 'blog_app:post_edit' pk=post.pk %}">Edit</a>
<a class='btn btn-primary' href="{% url 'blog_app:post_delete' pk=post.pk %}">Delete</a>
{% endif %}
{% endif %}
<div class='container'>
  -----------------------------------
{% for com in comment %}
<br>
 {{ com.text }}<br>
{% endfor %}
</div>
{% if user.is_authenticated  %}
<form method='POST' action = "{% url 'blog_app:post_comment' pk=post.pk %}">
  {% csrf_token %}
  <input type="submit" class='btn btn-primary btn-comment' value="Add Comment">
  <input type='hidden' name="next" value="{{next}}">
</form>
{% endif %}

{% endblock %}

blog_app/templates/blog_app/post_draft_list.html
<!DOCTYPE html>
{% extends "blog_app/base.html" %}
{% block content %}
{% endblock %}

blog_app/templates/blog_app/post_form.html
<!DOCTYPE html>
{% extends "blog_app/base.html" %}
{% block content %}
<div class='jumbotron'>
  <h3> MC likh abhi</h3>
  {% if form.errors %}
    <p>Galat hai bhai!</p>
  {% endif %}
  <form method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
  <input type='submit' class="btn btn-primary" value="Post">
  <input type='hidden' name="next" value="{{next}}">
  </form>

</div>
{% endblock %}

blog_app/templates/blog_app/post_list.html
<!DOCTYPE html>
{% load staticfiles }
{% extends "blog_app/base.html" %}
{% block content %}
{% if user.is_authenticated %}
<div class="centerstage">
  {% for post in post_list %}  <!-- 'post' is modelname and list is appended -->
  {% for fr in friends %}
  {% if post.author.username == fr.username %}
  <h1><a href="{% url 'blog_app:blog_post' pk=post.pk %}">{{ post.title }}</a></h1>
    <div class='disp_date'>
    <p>  Published at: {{ post.published_date }}</p>
    <p> Created By : {{ post.author }} </p>
    {% endif %}
    {% endfor %}
  {% endfor %}
    </div>
</div>
{% else %}
{% endif %}
{% endblock %}

blog_app/templates/blog_app/user_profile.html
<!DOCTYPE html>
{% extends "blog_app/base.html" %}
{% load staticfiles %}
{% block content %}
<div class="centerstage">
  <h1>{{ user.username }}</h1>
  {% if pp.profile_pic == null %}
  <form method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    {{ form_1.as_p }}
    <input type='submit' value='Upload'>
  </form>
  {% else %}
  <img src="{{ pp.profile_pic.url }}" width="240">
  {% endif %}
</div>
{% endblock %}